/**
 * Länderliste für die Staatsangehörigkeit (spiegelt makarim_crm/lib/countries.ts).
 * Gespeichert/gesendet wird der deutsche Ländername → im CRM konsistente Schreibweise.
 * Häufige Länder (Deutschland, Türkei, Marokko) stehen oben.
 */
export type Country = { code: string; de: string };

export const PRIORITY_CODES = ['DE', 'TR', 'MA'] as const;

export const COUNTRIES: Country[] = [
  { code: 'AF', de: 'Afghanistan' },
  { code: 'EG', de: 'Ägypten' },
  { code: 'AL', de: 'Albanien' },
  { code: 'DZ', de: 'Algerien' },
  { code: 'AD', de: 'Andorra' },
  { code: 'AO', de: 'Angola' },
  { code: 'AG', de: 'Antigua und Barbuda' },
  { code: 'GQ', de: 'Äquatorialguinea' },
  { code: 'AR', de: 'Argentinien' },
  { code: 'AM', de: 'Armenien' },
  { code: 'AZ', de: 'Aserbaidschan' },
  { code: 'ET', de: 'Äthiopien' },
  { code: 'AU', de: 'Australien' },
  { code: 'BS', de: 'Bahamas' },
  { code: 'BH', de: 'Bahrain' },
  { code: 'BD', de: 'Bangladesch' },
  { code: 'BB', de: 'Barbados' },
  { code: 'BE', de: 'Belgien' },
  { code: 'BZ', de: 'Belize' },
  { code: 'BJ', de: 'Benin' },
  { code: 'BT', de: 'Bhutan' },
  { code: 'BO', de: 'Bolivien' },
  { code: 'BA', de: 'Bosnien und Herzegowina' },
  { code: 'BW', de: 'Botswana' },
  { code: 'BR', de: 'Brasilien' },
  { code: 'BN', de: 'Brunei' },
  { code: 'BG', de: 'Bulgarien' },
  { code: 'BF', de: 'Burkina Faso' },
  { code: 'BI', de: 'Burundi' },
  { code: 'CL', de: 'Chile' },
  { code: 'CN', de: 'China' },
  { code: 'CR', de: 'Costa Rica' },
  { code: 'DK', de: 'Dänemark' },
  { code: 'DE', de: 'Deutschland' },
  { code: 'DM', de: 'Dominica' },
  { code: 'DO', de: 'Dominikanische Republik' },
  { code: 'DJ', de: 'Dschibuti' },
  { code: 'EC', de: 'Ecuador' },
  { code: 'SV', de: 'El Salvador' },
  { code: 'CI', de: 'Elfenbeinküste' },
  { code: 'ER', de: 'Eritrea' },
  { code: 'EE', de: 'Estland' },
  { code: 'SZ', de: 'Eswatini' },
  { code: 'FJ', de: 'Fidschi' },
  { code: 'FI', de: 'Finnland' },
  { code: 'FR', de: 'Frankreich' },
  { code: 'GA', de: 'Gabun' },
  { code: 'GM', de: 'Gambia' },
  { code: 'GE', de: 'Georgien' },
  { code: 'GH', de: 'Ghana' },
  { code: 'GD', de: 'Grenada' },
  { code: 'GR', de: 'Griechenland' },
  { code: 'GT', de: 'Guatemala' },
  { code: 'GN', de: 'Guinea' },
  { code: 'GW', de: 'Guinea-Bissau' },
  { code: 'GY', de: 'Guyana' },
  { code: 'HT', de: 'Haiti' },
  { code: 'HN', de: 'Honduras' },
  { code: 'IN', de: 'Indien' },
  { code: 'ID', de: 'Indonesien' },
  { code: 'IQ', de: 'Irak' },
  { code: 'IR', de: 'Iran' },
  { code: 'IE', de: 'Irland' },
  { code: 'IS', de: 'Island' },
  { code: 'IL', de: 'Israel' },
  { code: 'IT', de: 'Italien' },
  { code: 'JM', de: 'Jamaika' },
  { code: 'JP', de: 'Japan' },
  { code: 'YE', de: 'Jemen' },
  { code: 'JO', de: 'Jordanien' },
  { code: 'KH', de: 'Kambodscha' },
  { code: 'CM', de: 'Kamerun' },
  { code: 'CA', de: 'Kanada' },
  { code: 'CV', de: 'Kap Verde' },
  { code: 'KZ', de: 'Kasachstan' },
  { code: 'QA', de: 'Katar' },
  { code: 'KE', de: 'Kenia' },
  { code: 'KG', de: 'Kirgisistan' },
  { code: 'KI', de: 'Kiribati' },
  { code: 'CO', de: 'Kolumbien' },
  { code: 'KM', de: 'Komoren' },
  { code: 'CD', de: 'Kongo (Demokratische Republik)' },
  { code: 'CG', de: 'Kongo (Republik)' },
  { code: 'XK', de: 'Kosovo' },
  { code: 'HR', de: 'Kroatien' },
  { code: 'CU', de: 'Kuba' },
  { code: 'KW', de: 'Kuwait' },
  { code: 'LA', de: 'Laos' },
  { code: 'LS', de: 'Lesotho' },
  { code: 'LV', de: 'Lettland' },
  { code: 'LB', de: 'Libanon' },
  { code: 'LR', de: 'Liberia' },
  { code: 'LY', de: 'Libyen' },
  { code: 'LI', de: 'Liechtenstein' },
  { code: 'LT', de: 'Litauen' },
  { code: 'LU', de: 'Luxemburg' },
  { code: 'MG', de: 'Madagaskar' },
  { code: 'MW', de: 'Malawi' },
  { code: 'MY', de: 'Malaysia' },
  { code: 'MV', de: 'Malediven' },
  { code: 'ML', de: 'Mali' },
  { code: 'MT', de: 'Malta' },
  { code: 'MA', de: 'Marokko' },
  { code: 'MH', de: 'Marshallinseln' },
  { code: 'MR', de: 'Mauretanien' },
  { code: 'MU', de: 'Mauritius' },
  { code: 'MX', de: 'Mexiko' },
  { code: 'FM', de: 'Mikronesien' },
  { code: 'MD', de: 'Moldau' },
  { code: 'MC', de: 'Monaco' },
  { code: 'MN', de: 'Mongolei' },
  { code: 'ME', de: 'Montenegro' },
  { code: 'MZ', de: 'Mosambik' },
  { code: 'MM', de: 'Myanmar' },
  { code: 'NA', de: 'Namibia' },
  { code: 'NR', de: 'Nauru' },
  { code: 'NP', de: 'Nepal' },
  { code: 'NZ', de: 'Neuseeland' },
  { code: 'NI', de: 'Nicaragua' },
  { code: 'NL', de: 'Niederlande' },
  { code: 'NE', de: 'Niger' },
  { code: 'NG', de: 'Nigeria' },
  { code: 'KP', de: 'Nordkorea' },
  { code: 'MK', de: 'Nordmazedonien' },
  { code: 'NO', de: 'Norwegen' },
  { code: 'OM', de: 'Oman' },
  { code: 'AT', de: 'Österreich' },
  { code: 'PK', de: 'Pakistan' },
  { code: 'PW', de: 'Palau' },
  { code: 'PS', de: 'Palästina' },
  { code: 'PA', de: 'Panama' },
  { code: 'PG', de: 'Papua-Neuguinea' },
  { code: 'PY', de: 'Paraguay' },
  { code: 'PE', de: 'Peru' },
  { code: 'PH', de: 'Philippinen' },
  { code: 'PL', de: 'Polen' },
  { code: 'PT', de: 'Portugal' },
  { code: 'RW', de: 'Ruanda' },
  { code: 'RO', de: 'Rumänien' },
  { code: 'RU', de: 'Russland' },
  { code: 'SB', de: 'Salomonen' },
  { code: 'ZM', de: 'Sambia' },
  { code: 'WS', de: 'Samoa' },
  { code: 'SM', de: 'San Marino' },
  { code: 'ST', de: 'São Tomé und Príncipe' },
  { code: 'SA', de: 'Saudi-Arabien' },
  { code: 'SE', de: 'Schweden' },
  { code: 'CH', de: 'Schweiz' },
  { code: 'SN', de: 'Senegal' },
  { code: 'RS', de: 'Serbien' },
  { code: 'SC', de: 'Seychellen' },
  { code: 'SL', de: 'Sierra Leone' },
  { code: 'ZW', de: 'Simbabwe' },
  { code: 'SG', de: 'Singapur' },
  { code: 'SK', de: 'Slowakei' },
  { code: 'SI', de: 'Slowenien' },
  { code: 'SO', de: 'Somalia' },
  { code: 'ES', de: 'Spanien' },
  { code: 'LK', de: 'Sri Lanka' },
  { code: 'KN', de: 'St. Kitts und Nevis' },
  { code: 'LC', de: 'St. Lucia' },
  { code: 'VC', de: 'St. Vincent und die Grenadinen' },
  { code: 'ZA', de: 'Südafrika' },
  { code: 'SD', de: 'Sudan' },
  { code: 'KR', de: 'Südkorea' },
  { code: 'SS', de: 'Südsudan' },
  { code: 'SR', de: 'Suriname' },
  { code: 'SY', de: 'Syrien' },
  { code: 'TJ', de: 'Tadschikistan' },
  { code: 'TZ', de: 'Tansania' },
  { code: 'TH', de: 'Thailand' },
  { code: 'TL', de: 'Timor-Leste' },
  { code: 'TG', de: 'Togo' },
  { code: 'TO', de: 'Tonga' },
  { code: 'TT', de: 'Trinidad und Tobago' },
  { code: 'TD', de: 'Tschad' },
  { code: 'CZ', de: 'Tschechien' },
  { code: 'TN', de: 'Tunesien' },
  { code: 'TR', de: 'Türkei' },
  { code: 'TM', de: 'Turkmenistan' },
  { code: 'TV', de: 'Tuvalu' },
  { code: 'UG', de: 'Uganda' },
  { code: 'UA', de: 'Ukraine' },
  { code: 'HU', de: 'Ungarn' },
  { code: 'UY', de: 'Uruguay' },
  { code: 'UZ', de: 'Usbekistan' },
  { code: 'VU', de: 'Vanuatu' },
  { code: 'VA', de: 'Vatikanstadt' },
  { code: 'VE', de: 'Venezuela' },
  { code: 'AE', de: 'Vereinigte Arabische Emirate' },
  { code: 'US', de: 'Vereinigte Staaten' },
  { code: 'GB', de: 'Vereinigtes Königreich' },
  { code: 'VN', de: 'Vietnam' },
  { code: 'BY', de: 'Weißrussland' },
  { code: 'CF', de: 'Zentralafrikanische Republik' },
  { code: 'CY', de: 'Zypern' },
];

/** Häufige zuerst, dann der Rest alphabetisch. */
export function orderedCountries(): Country[] {
  const prio = PRIORITY_CODES.map((c) => COUNTRIES.find((x) => x.code === c)).filter((x): x is Country => !!x);
  const rest = COUNTRIES.filter((x) => !PRIORITY_CODES.includes(x.code as (typeof PRIORITY_CODES)[number])).sort((a, b) =>
    a.de.localeCompare(b.de, 'de'),
  );
  return [...prio, ...rest];
}
