import { CMSStore } from './content-schema';

export const defaultContent: CMSStore = {
  c: {
    home: {
      kicker: 'PILGERREISEN MIT SEELE',
      headline: 'Deine Reise zu den heiligen Stätten',
      sub: 'Erlebe authentische Pilgerfahrten nach Mekka, Medina und darüber hinaus — mit Fürsorge und Stil.',
      btnP: 'Reisen entdecken',
      btnS: 'Über uns',
      heroUrl: '/assets/examples/hero-a.jpg',
      featuredSection: {
        kicker: 'Aktuelle Reisen',
        title: 'Eine Auswahl unserer Reisen',
        linkText: 'Alle Reisen ansehen →',
        linkUrl: '/umrah-reisen',
      },
      stats: [
        { value: '40+', label: 'Jahre Erfahrung' },
        { value: '10.000+', label: 'Pilger betreut' },
        { value: '300+', label: 'organisierte Reisen' },
        { value: '100%', label: 'aus einer Hand' },
      ],
      trust: [
        { value: 'Rundum-Sorglos-Paket', label: 'Bei Makarim stehst Du im Mittelpunkt. Wir sorgen dafür, dass Du Dich von Anfang an wie in einer Familie willkommen und aufgehoben fühlst.' },
        { value: 'Jahrzehntelange Erfahrung', label: 'Über 40 Jahre Erfahrung in Hajj- und Umrah Reisen stehen für Vertrauen, Qualität und eine verlässliche Organisation.' },
        { value: 'Alles aus einer Hand', label: 'Visum, Flüge, Hotels und Verpflegung – wir kümmern uns um jedes Detail. So kannst Du Dich ganz auf Deine Umrah und Deine spirituelle Erfahrung konzentrieren.' },
        { value: 'Erstklassiger Service', label: 'Professionelles Team mit 24/7 Kontakt während Deiner gesamten Reise – organisatorisch und persönlich bestens betreut.' },
      ],
    },
    
    categories: [
      {
        key: 'umrah',
        name: 'Umrah',
        title: 'Umrah',
        description: 'Die kleine Pilgerfahrt — jederzeit möglich und erfüllend.',
        text: 'Umrah ist die kleine Pilgerfahrt — flexibel, jederzeit erlebbar und tief erfüllend.',
        icon: '🕋',
        url: 'umrah',
      },
      {
        key: 'hajj',
        name: 'Hajj',
        title: 'Hajj',
        description: 'Die große Pilgerfahrt — das zentrale Ereignis im Leben eines Muslims.',
        text: 'Hajj ist die große Pilgerfahrt — das zentrale Ereignis im Leben eines jeden Muslims.',
        icon: '🌙',
        url: 'hajj',
      },
      {
        key: 'kulturreisen',
        name: 'Kulturreisen',
        title: 'Kulturreisen',
        description: 'Islamische Geschichte und Architektur in Andalusien, Istanbul und Kairo.',
        text: 'Entdecke islamische Geschichte und Kultur in Andalusien, Istanbul und Kairo.',
        icon: '🏛️',
        url: 'kulturreisen',
      },
    ],
    
    trips: [
      {
        vg: '2026-0912',
        name: 'Umrah Luxus – Frühling',
        title: 'Umrah Frühling – Luxus im Haram',
        slug: 'umrah-luxus-fruehjahr',
        category: 'umrah',
        description: 'Luxus hautnah: Direkter Blick auf die Kaaba mit erstklassigen Hotels.',
        typ: 'Umrah',
        date: '15.–25. Mai 2026',
        nights: 10,
        price: 1890,
        status: 'verfügbar',
        text: 'Genießen Sie Luxus hautnah: Direkter Blick auf die Kaaba, erstklassige Betriebsamkeit und kulinarische Höhepunkte.',
        url: 'umrah-fruehjahr-luxus',
        startseite: true,
        published: true,
        seats: 24,
        waitlist: false,
        badge: 'Bestseller',
        heroIcon: '✨',
        banner: {
          enabled: false,
          line1: '',
          line2: '',
          color: '#C2724A',
        },
        seoTitle: '',
        seoDesc: '',
        hotels: [
          {
            city: 'Medina',
            name: 'Pullman Zamzam Madina',
            nights: '5 Nächte',
            rating: '9,3',
            dist: 'ca. 150 m zum Haram',
            photo: undefined,
          },
          {
            city: 'Mekka',
            name: 'Fairmont Makkah Clock Tower',
            nights: '5 Nächte',
            rating: '9,4',
            dist: 'ca. 100 m zum Haram',
            photo: undefined,
          },
        ],
        services: [
          'Unterkunft in 5-Sterne-Hotels',
          'Transfers Flughafen ↔ Hotel',
          'Haram-Führung mit zertifiziertem Reiseleiter',
          'Frühstück täglich',
          'Visa-Bearbeitung inklusive',
          '24/7 Betreuung vor Ort',
          'Kleine Gruppen (max. 25 Personen)',
          'Spirituelle Begleitung',
        ],
        program: [
          { day: 1, title: 'Anreise & Einleben', description: 'Flug nach Medina. Transfer zum Hotel Pullman Zamzam Madina. Erholung und erste Orientierung.' },
          { day: 2, title: 'Medina erkunden', description: 'Besuch der Propheten-Moschee (Masjid an-Nabawi). Besichtigung historischer Stätten in Medina.' },
          { day: 3, title: 'Spirituelle Vertiefung in Medina', description: 'Morgengebet in der Propheten-Moschee. Besuch von Quba-Moschee und Baqi-Friedhof.' },
          { day: 4, title: 'Transfer nach Mekka', description: 'Fahrt nach Mekka. Ihram anlegen und Ankunft im Fairmont Makkah. Erste Tawaf (Umkreisung der Kaaba).' },
          { day: 5, title: 'Umrah vollenden', description: 'Sa\'i zwischen Safa und Marwa. Haarschnitt und Abschluss der Umrah-Riten. Freie Zeit im Haram.' },
          { day: 6, title: 'Historische Stätten Mekkas', description: 'Besuch des Jabal al-Nour (Höhle Hira) und Jabal Thawr. Geführte Tour durch Alt-Mekka.' },
          { day: 7, title: 'Freier Tag in Mekka', description: 'Eigene Zeit für Gebete im Haram, Einkaufen und spirituelle Reflexion.' },
          { day: 8, title: 'Abschied vom Haram', description: 'Abschluss-Tawaf (Tawaf al-Wada). Transfer zum Flughafen Dschidda.' },
          { day: 9, title: 'Rückreise', description: 'Flug zurück nach Deutschland. Ankunft mit unvergesslichen Erinnerungen.' },
        ],
      },
      {
        vg: '2026-0513',
        name: 'Umrah Budget – Juni',
        title: 'Umrah Budget – Authentisch und Günstig',
        slug: 'umrah-budget-juni',
        category: 'umrah',
        description: 'Authentische Spiritualität ohne großen Preis — Umrah für alle.',
        typ: 'Umrah',
        date: '10.–18. Juni 2026',
        nights: 8,
        price: 1290,
        status: 'begrenzte Plätze',
        text: 'Erleben Sie die tiefe Spiritualität der Heiligen Stätten ohne großen Preis. Einfach, authentisch, erfüllend.',
        url: 'umrah-budget-authentisch',
        startseite: true,
        published: true,
        seats: 8,
        waitlist: false,
        badge: 'Nur noch 8 Plätze',
        heroIcon: '🌟',
        banner: {
          enabled: false,
          line1: '',
          line2: '',
          color: '#C2724A',
        },
        seoTitle: '',
        seoDesc: '',
        hotels: [
          {
            city: 'Medina',
            name: 'Al-Eairy Furnished Apartments',
            nights: '4 Nächte',
            rating: '8,1',
            dist: 'ca. 600 m zum Haram',
            photo: undefined,
          },
          {
            city: 'Mekka',
            name: 'Al-Noor Hotel',
            nights: '4 Nächte',
            rating: '7,8',
            dist: 'ca. 250 m zum Haram',
            photo: undefined,
          },
        ],
        services: [
          'Unterkunft im gebuchten Hotel',
          'Transfers Flughafen ↔ Hotel',
          'Haram-Führung mit Reiseleiter',
          'Frühstück täglich',
          'Visa-Bearbeitung inklusive',
          '24/7 Betreuung vor Ort',
        ],
        program: [
          { day: 1, title: 'Anreise nach Medina', description: 'Flug und Transfer zum Hotel. Erste Orientierung in Medina.' },
          { day: 2, title: 'Medina & Propheten-Moschee', description: 'Besuch der Propheten-Moschee und historischer Stätten.' },
          { day: 3, title: 'Transfer nach Mekka', description: 'Fahrt nach Mekka, Ihram anlegen, Tawaf und Sa\'i.' },
          { day: 4, title: 'Umrah vollenden & Haram', description: 'Vertiefung der spirituellen Praxis im Haram.' },
          { day: 5, title: 'Freier Tag', description: 'Eigene Zeit für Gebete, Einkäufe und Reflexion.' },
          { day: 6, title: 'Abschluss-Tawaf & Rückreise', description: 'Tawaf al-Wada, Transfer zum Flughafen, Heimflug.' },
        ],
      },
      {
        vg: '2026-0714',
        name: 'Hajj 2026 – Die große Pilgerfahrt',
        title: 'Hajj Paket 2026 – Die große Pilgerfahrt',
        slug: 'hajj-2026-vollstaendig',
        category: 'hajj',
        description: 'Vollständiges Hajj-Paket mit Führung und spiritueller Begleitung.',
        typ: 'Hajj',
        date: '8.–22. Juli 2026',
        nights: 14,
        price: 3590,
        status: 'ausgebucht',
        text: 'Vollständiges Hajj-Paket mit Führung, Unterkunft in gehobener Klasse und spiritueller Begleitung.',
        url: 'hajj-2026-vollstaendig',
        startseite: true,
        published: true,
        seats: 0,
        waitlist: true,
        badge: 'Warteliste verfügbar',
        heroIcon: '🙏',
        banner: {
          enabled: false,
          line1: '',
          line2: '',
          color: '#C2724A',
        },
        seoTitle: '',
        seoDesc: '',
        hotels: [
          {
            city: 'Medina',
            name: 'Radisson Blu',
            nights: '5 Nächte',
            rating: '9,0',
            dist: 'ca. 200 m zum Haram',
            photo: undefined,
          },
          {
            city: 'Mekka',
            name: 'Makkah Hilton',
            nights: '7 Nächte',
            rating: '9,2',
            dist: 'ca. 80 m zum Haram',
            photo: undefined,
          },
        ],
        services: [
          'Unterkunft in gehobenen Hotels',
          'Alle Hajj-Riten mit Führung',
          'Transfers & Inlandstransporte',
          'Vollpension während der Riten',
          'Visa-Bearbeitung inklusive',
          'Offizieller Hajj-Ausweis',
          '24/7 Betreuung & Notfallkontakt',
          'Spirituelle Begleitung durch Imam',
        ],
        program: [
          { day: 1, title: 'Anreise Medina', description: 'Flug nach Medina, Transfer und Empfang. Erste Nacht in der Heiligen Stadt.' },
          { day: 2, title: 'Propheten-Moschee', description: 'Morgengebet, Führung durch die Propheten-Moschee und historische Stätten Medinas.' },
          { day: 3, title: 'Medina – spirituelle Vertiefung', description: 'Besuch von Quba-Moschee, Baqi-Friedhof und Uhud-Schlachtfeld.' },
          { day: 4, title: 'Transfer nach Mekka', description: 'Reise nach Mekka, Ihram anlegen, Einzug in den Haram. Tawaf al-Qudum.' },
          { day: 5, title: 'Mekka & Haram', description: 'Sa\'i zwischen Safa und Marwa. Vorbereitung auf die Hajj-Riten.' },
          { day: 6, title: 'Mina', description: 'Aufenthalt in Mina (Tag der Tarwia). Nachtgebet und Vorbereitung.' },
          { day: 7, title: 'Arafat – Höhepunkt des Hajj', description: 'Aufenthalt auf der Ebene von Arafat (Tag des Wuquf). Abend: Transfer nach Muzdalifa.' },
          { day: 8, title: 'Muzdalifa & Mina', description: 'Nacht unter freiem Himmel in Muzdalifa. Morgens: Steinigungsritus in Mina.' },
          { day: 9, title: 'Eid al-Adha & Schlachtung', description: 'Opferfest. Haarschnitt, Ihram ablegen. Tawaf al-Ifada und Sa\'i.' },
          { day: 10, title: 'Ayyam at-Tashriq (1)', description: 'Weitere Steinigungen in Mina. Möglichkeit zur Rückkehr nach Mekka.' },
          { day: 11, title: 'Ayyam at-Tashriq (2)', description: 'Abschluss der Riten in Mina. Transfer zurück nach Mekka.' },
          { day: 12, title: 'Abschluss-Tawaf', description: 'Tawaf al-Wada. Abschied von der Kaaba. Transfer zum Flughafen.' },
          { day: 13, title: 'Rückreise', description: 'Flug nach Deutschland. Als Hajji kehrt man erneuert heim.' },
        ],
      },
      {
        vg: '2026-1025',
        name: 'Granada & Córdoba – Al-Andalus',
        title: 'Granada & Córdoba – Islamische Schätze in Spanien',
        slug: 'granada-cordoba-al-andalus',
        category: 'kulturreisen',
        description: 'Folgen Sie den Spuren der Al-Andalus-Ära: Alhambra, Moschee, versteckte Paläste.',
        typ: 'Kulturreisen',
        date: '5.–12. Oktober 2026',
        nights: 7,
        price: 1490,
        status: 'verfügbar',
        text: 'Folgen Sie den Spuren der Al-Andalus-Ära: Alhambra, Große Moschee von Córdoba, versteckte Paläste.',
        url: 'granada-cordoba-al-andalus',
        startseite: false,
        published: true,
        seats: 18,
        waitlist: false,
        heroIcon: '🕌',
        hotels: [],
        program: [
          { day: 'Tag 1', title: 'Ankunft in Sevilla', description: 'Flug und Transfer nach Sevilla. Einleben im Hotel und erster Abendspaziergang durch die Altstadt.' },
          { day: 'Tag 2', title: 'Sevilla – Alcázar & Kathedrale', description: 'Besuch des Real Alcázar, eines der schönsten Mudéjar-Bauwerke Spaniens, und der gotischen Kathedrale.' },
          { day: 'Tag 3', title: 'Transfer nach Córdoba', description: 'Fahrt nach Córdoba. Besuch der Großen Moschee (Mezquita-Catedral) – dem Herzstück der islamischen Architektur in Spanien.' },
          { day: 'Tag 4', title: 'Córdoba – Medina Azahara', description: 'Ausflug zur Palaststadt Medina Azahara. Nachmittags: Spaziergang durch das jüdische Viertel und den Souk.' },
          { day: 'Tag 5', title: 'Transfer nach Granada', description: 'Fahrt nach Granada. Ankunft und Abendspaziergang auf dem Mirador de San Nicolás mit Blick auf die Alhambra.' },
          { day: 'Tag 6', title: 'Granada – Alhambra & Generalife', description: 'Ganztägige Führung durch die Alhambra: Nasridenpaläste, Alcazaba und die Gärten des Generalife.' },
          { day: 'Tag 7', title: 'Granada – Albaicín & Moschee', description: 'Besuch des Albaicín-Viertels und der neuen Moschee von Granada. Freie Zeit für Einkäufe und Reflexion.' },
          { day: 'Tag 8', title: 'Rückreise', description: 'Transfer zum Flughafen Málaga. Heimflug mit unvergesslichen Eindrücken von Al-Andalus.' },
        ],
      },
    ],
    
    faq: [
      {
        q: 'Wer kann an den Umrah-Reisen teilnehmen?',
        a: 'Alle Muslime, die körperlich und mental fit sind. Kinder ab 10 Jahren können mit Erwachsenen teilnehmen.',
      },
      {
        q: 'Gibt es Visaverwaltung?',
        a: 'Ja, wir kümmern uns um alle Visa-Formalitäten. In den Paketgebühren enthalten.',
      },
      {
        q: 'Werden Flüge incluso?',
        a: 'Flüge sind standardmäßig nicht enthalten, können aber hinzugebucht werden.',
      },
      {
        q: 'Was ist im Paket enthalten?',
        a: 'Hotel (laut Paket), Transfers, Haram-Führungen, Mahlzeiten, Reiseführer und 24/7-Support.',
      },
    ],

    // Ratgeber & Galerie werden im CMS gepflegt (Admin → Ratgeber / Galerie).
    guides: [],
    gallery: [],

    // Rechtstexte werden im CMS gepflegt (Admin → Rechtliches). Inhalt vom Betreiber.
    legal: { impressum: '', agb: '', datenschutz: '' },

    about: {
      title: 'Über Makarim – Reisen mit Seele',
      body: 'Seit 15 Jahren begleiten wir Pilger auf ihrer spirituellen Reise. Makarim bedeutet "Tugenden" — und diese leiten uns jeden Tag: Authentizität, Sorgfalt, Treue.',
      url: '/assets/examples/about-1.jpg',
      url2: '/assets/examples/about-2.jpg',
      whyTitle: 'Warum Makarim?',
      whyBody: 'Wir verbinden traditionelle Werte mit modernem Komfort. Kein Mass-Tourism, sondern persönliche Betreuung, durchdachte Reisen und echte Mehrwerte für Pilger und ihre Familien.',
      tiles: [
        { t: 'Kleine Gruppen', b: 'Max. 25 Personen pro Reise für persönliche Betreuung.' },
        { t: 'Lokal vernetzt', b: 'Partner vor Ort, die du persönlich kennen lernst.' },
        { t: 'Nachhaltig', b: 'Respekt für Kultur, Umwelt und die heiligen Stätten.' },
        { t: '24/7 Support', b: 'Erreichbar, egal wo du bist.' },
      ],
    },
    
    cta: {
      headline: 'Bereit für deine spirituelle Reise?',
      sub: 'Lass dich inspirieren und stelle deine Fragen.',
      btnCall: 'Anrufen',
      btnWrite: 'Schreiben',
    },
    
    brand: {
      phone: '+49 30 12345678',
      whatsapp: '4915114575859',
      email: 'hello@makarim.de',
      instagram: '@makarim_reisen',
      address1: 'Makarim GmbH',
      address2: 'Kurfürstendamm 123, 10711 Berlin, Deutschland',
      footerCopyright: `© ${new Date().getFullYear()} Makarim GmbH · Alle Rechte vorbehalten`,
      footerTagline: 'Pilgerreisen mit Seele',
      kontaktHeading: 'Wir sind für dich da',
      kontaktIntro: 'Hast du eine Frage zu einer Reise, möchtest dich beraten lassen oder brauchst Hilfe bei deiner Buchung? Schreib uns – wir melden uns persönlich bei dir.',
      bookingEmail: {
        intro: 'vielen Dank für Ihre Buchungsanfrage. Wir haben Ihre Anfrage erhalten und werden uns innerhalb von 24 Stunden bei Ihnen melden, um alle weiteren Details zu besprechen.',
        step1Title: 'Wir bestätigen Ihre Anfrage',
        step1Text: 'Sie erhalten innerhalb von 24 Stunden eine Buchungsbestätigung per E-Mail.',
        step2Title: 'Anzahlung überweisen',
        step2Text: 'Nach Bestätigung überweisen Sie bitte die Anzahlung auf unser Konto.',
        step3Title: 'Reiseunterlagen',
        step3Text: 'Ca. 4 Wochen vor Reisebeginn erhalten Sie alle Unterlagen.',
      },
      bank: {
        inhaber: 'Makarim GmbH',
        iban: 'DE12 1234 5678 9012 3456 78',
        bic: 'DEUT DEDBBER',
        name: 'Deutsche Bank',
      },
    },
    
    seo: {
      siteName: 'Makarim – Pilgerreisen mit Seele',
      defaultDesc: 'Entdecke spirituelle Pilgerreisen zu den heiligen Stätten und islamische Kulturreisen. Kleine Gruppen, persönliche Betreuung, authentische Erlebnisse.',
      home: {
        title: 'Makarim – Pilgerreisen zu den heiligen Stätten',
        desc: 'Erleben Sie Hajj und Umrah in Mekka und Medina sowie islamische Kulturreisen. Mit 15+ Jahren Erfahrung und persönlicher Betreuung.',
      },
      umrah: {
        title: 'Umrah-Reisen – Die kleine Pilgerfahrt flexibel erleben',
        desc: 'Umrah-Paket für jedes Budget. Vom Luxus bis authentisch günstig. Inklusive Unterkunft, Haram-Führung und Support.',
      },
      hajj: {
        title: 'Hajj 2026 – Die große Pilgerfahrt mit Makarim',
        desc: 'Hajj-Paket 2026 mit Hotel, Führung und spiritueller Begleitung. Alle Riten, keine Hektik.',
      },
      kultur: {
        title: 'Islamische Kulturreisen – Geschichte hautnah',
        desc: 'Granada, Istanbul, Kairo: Entdecke Schätze der islamischen Zivilisation auf geführten Touren.',
      },
      about: {
        title: 'Über Makarim – 15 Jahre Reiseerfahrung',
        desc: 'Lernen Sie unser Team kennen. Spiritualität, Authentizität, persönliche Betreuung seit 2011.',
      },
    },
  },
  
  media: [],
};
